zuul:
  routes:
    adminui:
      path: /**
      url: http://localhost:4200/
        
  logging:
    level:
      org.springframework.web: 'debug'
      org.springframework.hateoas: 'debug'
  spring:
    jackson:
      serialization:
        indent_output: 'true'